inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/migrate/*.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
